# Generated by Django 5.1.2 on 2025-03-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_range',
            field=models.CharField(blank=True, choices=[('500-1000', '₱500 - ₱1,000'), ('1000-2000', '₱1,000 - ₱2,000'), ('3000-5000', '₱3,000 - ₱5,000')], max_length=20, null=True),
        ),
    ]
