# Generated by Django 5.1.2 on 2025-03-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_product_price_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='ericashoeline/blog_images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default_category.jpg', upload_to='ericashoeline/category_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_product.jpg', upload_to='ericashoeline/product_images/'),
        ),
        migrations.AlterField(
            model_name='productcollection',
            name='image',
            field=models.ImageField(upload_to='ericashoeline/collections/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='ericashoeline/team/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='ericashoeline/testimonials/'),
        ),
    ]
