# Generated by Django 5.1.2 on 2025-03-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_aboutsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
