# Generated by Django 5.1.2 on 2025-06-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
