# Generated by Django 5.1.2 on 2025-06-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_order_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='district',
        ),
    ]
