# Generated by Django 5.1.2 on 2025-06-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_order_province_order_region_order_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('preparing', 'Preparing'), ('to_ship', 'To Ship'), ('shipped', 'Shipped')], default='received', max_length=20),
        ),
    ]
